/*
 * Copyright (C) Cvitek Co., Ltd. 2019-2020. All rights reserved.
 *
 * File Name: cvi_vc_drv_ioctl.h
 * Description:
 */

#ifndef __CVI_VC_DRV_IOCTL_H__
#define __CVI_VC_DRV_IOCTL_H__

#include "osal_ioctl.h"

#define CVI_VC_DRV_ENCODER_DEV_NAME         "soph-vc-enc"
#define CVI_VC_DRV_DECODER_DEV_NAME         "soph-vc-dec"

#define CVI_VC_DRV_IOCTL_MAGIC              'V'
/* encoder ioctl */
#define CVI_VC_VENC_CREATE_CHN              _IOW(CVI_VC_DRV_IOCTL_MAGIC, 0, VENC_CHN_ATTR_S)
#define CVI_VC_VENC_DESTROY_CHN             _IO(CVI_VC_DRV_IOCTL_MAGIC, 1)
#define CVI_VC_VENC_RESET_CHN               _IO(CVI_VC_DRV_IOCTL_MAGIC, 2)
#define CVI_VC_VENC_START_RECV_FRAME        _IOW(CVI_VC_DRV_IOCTL_MAGIC, 3, VENC_RECV_PIC_PARAM_S)
#define CVI_VC_VENC_STOP_RECV_FRAME         _IO(CVI_VC_DRV_IOCTL_MAGIC, 4)
#define CVI_VC_VENC_QUERY_STATUS            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 5, VENC_CHN_STATUS_S)
#define CVI_VC_VENC_SET_CHN_ATTR            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 6, VENC_CHN_ATTR_S)
#define CVI_VC_VENC_GET_CHN_ATTR            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 7, VENC_CHN_ATTR_S)
#define CVI_VC_VENC_GET_STREAM              _IOR(CVI_VC_DRV_IOCTL_MAGIC, 8, VENC_STREAM_EX_S)
#define CVI_VC_VENC_RELEASE_STREAM          _IOW(CVI_VC_DRV_IOCTL_MAGIC, 9, VENC_STREAM_S)
#define CVI_VC_VENC_INSERT_USERDATA         _IOW(CVI_VC_DRV_IOCTL_MAGIC, 10, VENC_USER_DATA_S)
#define CVI_VC_VENC_SEND_FRAME              _IOW(CVI_VC_DRV_IOCTL_MAGIC, 11, VIDEO_FRAME_INFO_EX_S)
#define CVI_VC_VENC_SEND_FRAMEEX            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 12, USER_FRAME_INFO_EX_S)
#define CVI_VC_VENC_REQUEST_IDR             _IOW(CVI_VC_DRV_IOCTL_MAGIC, 13, CVI_BOOL)
#define CVI_VC_VENC_SET_ROI_ATTR            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 14, VENC_ROI_ATTR_S)
#define CVI_VC_VENC_GET_ROI_ATTR            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 15, VENC_ROI_ATTR_S)
#define CVI_VC_VENC_SET_H264_TRANS          _IOW(CVI_VC_DRV_IOCTL_MAGIC, 16, VENC_H264_TRANS_S)
#define CVI_VC_VENC_GET_H264_TRANS          _IOR(CVI_VC_DRV_IOCTL_MAGIC, 17, VENC_H264_TRANS_S)
#define CVI_VC_VENC_SET_H264_ENTROPY        _IOW(CVI_VC_DRV_IOCTL_MAGIC, 18, VENC_H264_ENTROPY_S)
#define CVI_VC_VENC_GET_H264_ENTROPY        _IOR(CVI_VC_DRV_IOCTL_MAGIC, 19, VENC_H264_ENTROPY_S)
#define CVI_VC_VENC_SET_H264_VUI            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 20, VENC_H264_VUI_S)
#define CVI_VC_VENC_GET_H264_VUI            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 21, VENC_H264_VUI_S)
#define CVI_VC_VENC_SET_H265_VUI            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 22, VENC_H265_VUI_S)
#define CVI_VC_VENC_GET_H265_VUI            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 23, VENC_H265_VUI_S)
#define CVI_VC_VENC_SET_JPEG_PARAM          _IOW(CVI_VC_DRV_IOCTL_MAGIC, 24, VENC_JPEG_PARAM_S)
#define CVI_VC_VENC_GET_JPEG_PARAM          _IOR(CVI_VC_DRV_IOCTL_MAGIC, 25, VENC_JPEG_PARAM_S)
#define CVI_VC_VENC_GET_RC_PARAM            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 26, VENC_RC_PARAM_S)
#define CVI_VC_VENC_SET_RC_PARAM            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 27, VENC_RC_PARAM_S)
#define CVI_VC_VENC_SET_REF_PARAM           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 28, VENC_REF_PARAM_S)
#define CVI_VC_VENC_GET_REF_PARAM           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 29, VENC_REF_PARAM_S)
#define CVI_VC_VENC_SET_H265_TRANS          _IOW(CVI_VC_DRV_IOCTL_MAGIC, 30, VENC_H265_TRANS_S)
#define CVI_VC_VENC_GET_H265_TRANS          _IOR(CVI_VC_DRV_IOCTL_MAGIC, 31, VENC_H265_TRANS_S)
#define CVI_VC_VENC_SET_FRAMELOST_STRATEGY  _IOW(CVI_VC_DRV_IOCTL_MAGIC, 32, VENC_FRAMELOST_S)
#define CVI_VC_VENC_GET_FRAMELOST_STRATEGY  _IOR(CVI_VC_DRV_IOCTL_MAGIC, 33, VENC_FRAMELOST_S)
#define CVI_VC_VENC_SET_SUPERFRAME_STRATEGY _IOW(CVI_VC_DRV_IOCTL_MAGIC, 34, VENC_SUPERFRAME_CFG_S)
#define CVI_VC_VENC_GET_SUPERFRAME_STRATEGY _IOR(CVI_VC_DRV_IOCTL_MAGIC, 35, VENC_SUPERFRAME_CFG_S)
#define CVI_VC_VENC_SET_CHN_PARAM           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 36, VENC_CHN_PARAM_S)
#define CVI_VC_VENC_GET_CHN_PARAM           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 37, VENC_CHN_PARAM_S)
#define CVI_VC_VENC_SET_MOD_PARAM           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 38, VENC_PARAM_MOD_S)
#define CVI_VC_VENC_GET_MOD_PARAM           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 39, VENC_PARAM_MOD_S)
#define CVI_VC_VENC_ATTACH_VBPOOL           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 40, VENC_CHN_POOL_S)
#define CVI_VC_VENC_DETACH_VBPOOL           _IO(CVI_VC_DRV_IOCTL_MAGIC, 41)
#define CVI_VC_VENC_SET_CUPREDICTION        _IOW(CVI_VC_DRV_IOCTL_MAGIC, 42, VENC_CU_PREDICTION_S)
#define CVI_VC_VENC_GET_CUPREDICTION        _IOR(CVI_VC_DRV_IOCTL_MAGIC, 43, VENC_CU_PREDICTION_S)
#define CVI_VC_VENC_CALC_FRAME_PARAM        _IOW(CVI_VC_DRV_IOCTL_MAGIC, 44, VENC_FRAME_PARAM_S)
#define CVI_VC_VENC_SET_FRAME_PARAM         _IOW(CVI_VC_DRV_IOCTL_MAGIC, 45, VENC_FRAME_PARAM_S)
#define CVI_VC_VENC_GET_FRAME_PARAM         _IOR(CVI_VC_DRV_IOCTL_MAGIC, 46, VENC_FRAME_PARAM_S)
/* decoder ioctl */
#define CVI_VC_VDEC_CREATE_CHN              _IOW(CVI_VC_DRV_IOCTL_MAGIC, 47, VDEC_CHN_ATTR_S)
#define CVI_VC_VDEC_DESTROY_CHN             _IO(CVI_VC_DRV_IOCTL_MAGIC, 48)
#define CVI_VC_VDEC_GET_CHN_ATTR            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 49, VDEC_CHN_ATTR_S)
#define CVI_VC_VDEC_SET_CHN_ATTR            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 50, VDEC_CHN_ATTR_S)
#define CVI_VC_VDEC_START_RECV_STREAM       _IO(CVI_VC_DRV_IOCTL_MAGIC, 51)
#define CVI_VC_VDEC_STOP_RECV_STREAM        _IO(CVI_VC_DRV_IOCTL_MAGIC, 52)
#define CVI_VC_VDEC_QUERY_STATUS            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 53, VDEC_CHN_STATUS_S)
#define CVI_VC_VDEC_RESET_CHN               _IO(CVI_VC_DRV_IOCTL_MAGIC, 54)
#define CVI_VC_VDEC_SET_CHN_PARAM           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 55, VDEC_CHN_PARAM_S)
#define CVI_VC_VDEC_GET_CHN_PARAM           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 56, VDEC_CHN_PARAM_S)
#define CVI_VC_VDEC_SEND_STREAM             _IOW(CVI_VC_DRV_IOCTL_MAGIC, 57, VDEC_STREAM_EX_S)
#define CVI_VC_VDEC_GET_FRAME               _IOR(CVI_VC_DRV_IOCTL_MAGIC, 58, VIDEO_FRAME_INFO_EX_S)
#define CVI_VC_VDEC_RELEASE_FRAME           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 59, VIDEO_FRAME_INFO_S)
#define CVI_VC_VDEC_ATTACH_VBPOOL           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 60, VDEC_CHN_POOL_S)
#define CVI_VC_VDEC_DETACH_VBPOOL           _IO(CVI_VC_DRV_IOCTL_MAGIC, 61)
#define CVI_VC_VDEC_SET_MOD_PARAM           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 62, VDEC_MOD_PARAM_S)
#define CVI_VC_VDEC_GET_MOD_PARAM           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 63, VDEC_MOD_PARAM_S)
#define CVI_VC_DECODE_H265_TEST             _IO(CVI_VC_DRV_IOCTL_MAGIC, 64)
#define CVI_VC_DECODE_H264_TEST             _IO(CVI_VC_DRV_IOCTL_MAGIC, 65)
#define CVI_VC_ENCODE_MAIN_TEST             _IO(CVI_VC_DRV_IOCTL_MAGIC, 66)
#define CVI_VC_ENC_DEC_JPEG_TEST            _IO(CVI_VC_DRV_IOCTL_MAGIC, 67)

/* encoder slice split */
#define CVI_VC_VENC_SET_H264_SLICE_SPLIT    _IOW(CVI_VC_DRV_IOCTL_MAGIC, 68, VENC_H264_SLICE_SPLIT_S)
#define CVI_VC_VENC_GET_H264_SLICE_SPLIT    _IOR(CVI_VC_DRV_IOCTL_MAGIC, 69, VENC_H264_SLICE_SPLIT_S)
#define CVI_VC_VENC_SET_H265_SLICE_SPLIT    _IOW(CVI_VC_DRV_IOCTL_MAGIC, 70, VENC_H265_SLICE_SPLIT_S)
#define CVI_VC_VENC_GET_H265_SLICE_SPLIT    _IOR(CVI_VC_DRV_IOCTL_MAGIC, 71, VENC_H265_SLICE_SPLIT_S)
/* encoder ioctl */
#define CVI_VC_VENC_GET_H264_DBLK           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 72, VENC_H264_DBLK_S)
#define CVI_VC_VENC_SET_H264_DBLK           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 73, VENC_H264_DBLK_S)
#define CVI_VC_VENC_GET_H265_DBLK           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 74, VENC_H265_DBLK_S)
#define CVI_VC_VENC_SET_H265_DBLK           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 75, VENC_H265_DBLK_S)

#define CVI_VC_VENC_SET_H264_INTRA_PRED    _IOW(CVI_VC_DRV_IOCTL_MAGIC, 76, VENC_H264_INTRA_PRED_S)
#define CVI_VC_VENC_GET_H264_INTRA_PRED    _IOR(CVI_VC_DRV_IOCTL_MAGIC, 77, VENC_H264_INTRA_PRED_S)
#define CVI_VC_VENC_ENC_JPEG_TEST          _IO(CVI_VC_DRV_IOCTL_MAGIC, 78)
#define CVI_VC_VDEC_DEC_JPEG_TEST          _IO(CVI_VC_DRV_IOCTL_MAGIC, 79)
#define CVI_VC_VDEC_FRAME_ADD_USER         _IO(CVI_VC_DRV_IOCTL_MAGIC, 80, VIDEO_FRAME_INFO_S)
#define CVI_VC_VENC_SET_CUSTOM_MAP         _IO(CVI_VC_DRV_IOCTL_MAGIC, 81)
#define CVI_VC_VENC_GET_INTINAL_INFO       _IO(CVI_VC_DRV_IOCTL_MAGIC, 82)
#define CVI_VC_VENC_SET_H265_SAO           _IOW(CVI_VC_DRV_IOCTL_MAGIC, 83, VENC_H265_SAO_S)
#define CVI_VC_VENC_GET_H265_SAO           _IOR(CVI_VC_DRV_IOCTL_MAGIC, 84, VENC_H265_SAO_S)
#define CVI_VC_VENC_GET_HEADER             _IO(CVI_VC_DRV_IOCTL_MAGIC, 85)
#define CVI_VC_VENC_GET_EXT_ADDR           _IO(CVI_VC_DRV_IOCTL_MAGIC, 86)

#define CVI_VC_VCODEC_SET_CHN               _IOW(CVI_VC_DRV_IOCTL_MAGIC, 100, VENC_CHN)
#define CVI_VC_VCODEC_GET_CHN               _IOR(CVI_VC_DRV_IOCTL_MAGIC, 101, VENC_CHN)

#define CVI_VC_VENC_SET_MJPEG_PARAM            _IOW(CVI_VC_DRV_IOCTL_MAGIC, 102, VENC_MJPEG_PARAM_S)
#define CVI_VC_VENC_GET_MJPEG_PARAM            _IOR(CVI_VC_DRV_IOCTL_MAGIC, 103, VENC_MJPEG_PARAM_S)
#define CVI_VC_VENC_ENABLE_IDR                 _IOW(CVI_VC_DRV_IOCTL_MAGIC, 104, CVI_BOOL)
#define CVI_VC_VENC_SET_H265_PRED_UNIT         _IOW(CVI_VC_DRV_IOCTL_MAGIC, 105, VENC_H265_PU_S)
#define CVI_VC_VENC_GET_H265_PRED_UNIT         _IOR(CVI_VC_DRV_IOCTL_MAGIC, 106, VENC_H265_PU_S)
#define CVI_VC_VENC_ENABLE_SVC                 _IOW(CVI_VC_DRV_IOCTL_MAGIC, 107, CVI_BOOL)
#define CVI_VC_VENC_SET_SVC_PARAM              _IOW(CVI_VC_DRV_IOCTL_MAGIC, 108, VENC_SVC_PARAM_S)
#define CVI_VC_VENC_GET_SVC_PARAM              _IOR(CVI_VC_DRV_IOCTL_MAGIC, 109, VENC_SVC_PARAM_S)
#define CVI_VC_VENC_SET_BACKHOE_HWCFG          _IO(CVI_VC_DRV_IOCTL_MAGIC, 114)
#define CVI_VC_VENC_GET_BACKHOE_HWCFG          _IO(CVI_VC_DRV_IOCTL_MAGIC, 115)

#endif /* __CVI_VC_DRV_IOCTL_H__ */

