#ifndef __MSG_AUDIO_H__
#define __MSG_AUDIO_H__

#include "msg.h"

typedef enum tagMSG_AUDIO_CMD_E {
	MSG_CMD_AUDIO_AI_OPEN = 0,
	MSG_CMD_AUDIO_AO_OPEN,
	MSG_CMD_AUDIO_AI_CLOSE,
	MSG_CMD_AUDIO_AO_CLOSE,
	MSG_CMD_AUDIO_SET_VOL,
	MSG_CMD_AUDIO_GET_VOL,
	MSG_CMD_AUDIO_SET_STEREO_VOL,
	MSG_CMD_AUDIO_GET_STEREO_VOL,
	MSG_CMD_AUDIO_SET_MUTE,
	MSG_CMD_AUDIO_GET_MUTE,
	MSG_CMD_AUDIO_SSP_OPEN,
	MSG_CMD_AUDIO_SSP_CLOSE,
} MSG_AUDIO_CMD_E;


#endif
