#ifndef __MSG_SENSOR_H__
#define __MSG_SENSOR_H__

#include "msg.h"

typedef enum tagMSG_SENSOR_CMD_E {
	MSG_CMD_SENSOR_EN_AHD_THREAD = 0,
	MSG_CMD_SENSOR_GET_STATUS,
	MSG_CMD_SENSOR_SET_AHD_INIT,
	MSG_CMD_SENSOR_SET_AHD_DEINIT,
	MSG_CMD_SENSOR_SET_AHD_MODE,
	MSG_CMD_SENSOR_GET_AHD_MODE,
	MSG_CMD_SENSOR_SET_AHD_BUSINFO,
	MSG_CMD_SENSOR_DETECT_AHD_STATUS,
	MSG_CMD_SENSOR_SET_RX_ATTR,
	MSG_CMD_SENSOR_SET_SNS_I2C,
	MSG_CMD_SENSOR_SET_ISP_INIT,
	MSG_CMD_SENSOR_ISP_REG_CB,
	MSG_CMD_SENSOR_ISP_UNREG_CB,
	MSG_CMD_SENSOR_SET_IMG_MODE,
	MSG_CMD_SENSOR_SET_WDR_MODE,
	MSG_CMD_SENSOR_GET_RX_ATTR,
	MSG_CMD_SENSOR_SET_SNS_PROBE,
	MSG_CMD_SENSOR_RESET_GPIO,
	MSG_CMD_SENSOR_RESET_MIPI,
	MSG_CMD_SENSOR_SET_MIPI_ATTR,
	MSG_CMD_SENSOR_EN_SNS_CLK,
	MSG_CMD_SENSOR_SET_SNS_CLK,
	MSG_CMD_SENSOR_SET_OUTPUT_CLK_EDGE,
	MSG_CMD_SENSOR_SET_SNS_STANDBY,
	MSG_CMD_SENSOR_SET_SNS_RESTART,
	MSG_CMD_SENSOR_SET_SNS_INIT,
	MSG_CMD_SENSOR_SET_FLIPMIRROR_CB,
	MSG_CMD_SENSOR_GET_AE_DEFAULT,
	MSG_CMD_SENSOR_GET_BLK_LEVEL,
	MSG_CMD_SENSOR_SET_SNS_FPS,
	MSG_CMD_SENSOR_GET_EXP_RAT,
	MSG_CMD_SENSOR_SET_DGAIN_CALC,
	MSG_CMD_SENSOR_SET_AGAIN_CALC,
	MSG_CMD_SENSOR_GET_CONFIG_INFO,
	MSG_CMD_SENSOR_SET_DRV_CFG,
} MSG_SENSOR_CMD_E;

#endif
