#ifndef __MSG_MIPI_TX_H__
#define __MSG_MIPI_TX_H__

#include "msg.h"

typedef enum tagMSG_MIPI_TX_CMD_E {
	MSG_CMD_MIPI_TX_SET_DEV_CFG = 0,
	MSG_CMD_MIPI_TX_SET_CMD,
	MSG_CMD_MIPI_TX_GET_CMD,
	MSG_CMD_MIPI_TX_ENABLE,
	MSG_CMD_MIPI_TX_DISABLE,
	MSG_CMD_MIPI_TX_SET_HS_SETTLE,
	MSG_CMD_MIPI_TX_GET_HS_SETTLE,
} MSG_MIPI_TX_CMD_E;

#endif
