#ifndef __MSG_VB_H__
#define __MSG_VB_H__

#include "msg.h"

typedef enum tagMSG_VB_CMD_E {
	MSG_CMD_VB_INIT = 0,
	MSG_CMD_VB_EXIT,
	MSG_CMD_VB_SET_CONFIG,
	MSG_CMD_VB_GET_CONFIG,
	MSG_CMD_VB_CREATE_POOL,
	MSG_CMD_VB_CREATE_EX_POOL,
	MSG_CMD_VB_DESTROY_POOL,
	MSG_CMD_VB_GET_BLOCK,
	MSG_CMD_VB_RELEASE_BLOCK,
	MSG_CMD_VB_PHYS_ADDR2_HANDLE,
	MSG_CMD_VB_HANDLE2_PHYS_ADDR,
	MSG_CMD_VB_HANDLE2_POOL_ID,
	MSG_CMD_VB_INQUIRE_USER_CNT,
	MSG_CMD_VB_PRINT_POOL
} MSG_VB_CMD_E;


#endif
