#ifndef __MSG_VDEC_H__
#define __MSG_VDEC_H__

#include "msg.h"

typedef enum tagMSG_VDEC_CMD_E {
	MSG_CMD_VDEC_CREATE_CHN = 0,
	MSG_CMD_VDEC_DESTROY_CHN,
	MSG_CMD_VDEC_SET_CHN_ATTR,
	MSG_CMD_VDEC_GET_CHN_ATTR,
	MSG_CMD_VDEC_START_RECV_FRAME,
	MSG_CMD_VDEC_STOP_RECV_FRAME,
	MSG_CMD_VDEC_RESET_CHN,
	MSG_CMD_VDEC_SET_CHN_PARAM,
	MSG_CMD_VDEC_GET_CHN_PARAM,
	MSG_CMD_VDEC_SEND_STREAM,
	MSG_CMD_VDEC_GET_FRAME,
	MSG_CMD_VDEC_RELEASE_FRAME,
	MSG_CMD_VDEC_ATTACH_VBPOOL,
	MSG_CMD_VDEC_DETACH_VBPOOL,
	MSG_CMD_VDEC_SET_MOD_PARAM,
	MSG_CMD_VDEC_GET_MOD_PARAM,
	MSG_CMD_VDEC_QUERY_STATUS,
	MSG_CMD_VDEC_ION_ALLOC,
	MSG_CMD_VDEC_ION_FREE,
	MSG_CMD_VDEC_GET_FIRMWARE_STRATEGY,
	MSG_CMD_VDEC_SUSPEND,
	MSG_CMD_VDEC_RESUME,
} MSG_DEC_CMD_E;

#endif
