#ifndef __MSG_ISP_H__
#define __MSG_ISP_H__

#include "msg.h"

typedef enum tagMSG_ISP_CMD_E {
	MSG_CMD_ISP_INIT,
	MSG_CMD_ISP_EXIT,
	MSG_CMD_ISP_MEM_INIT,
	MSG_CMD_ISP_SET_FMW_STATE,
	MSG_CMD_ISP_GET_FMW_STATE,
	MSG_CMD_ISP_GET_VD_TIMEOUT,
	MSG_CMD_ISP_SET_SMART_INFO,
	MSG_CMD_ISP_GET_SMART_INFO,
	MSG_CMD_ISP_GET_ION_INFO,
	MSG_CMD_ISP_AE_GET_BUF_SIZE,
	MSG_CMD_ISP_AE_GET_BUF,
	MSG_CMD_ISP_AE_SET_RAW_DUMP_FID,
	MSG_CMD_ISP_AE_GET_RAW_REPLAY_EXP_BUF,
	MSG_CMD_ISP_AE_SET_RAW_REPLAY_EXPOSURE,
	MSG_CMD_ISP_AE_GET_BIN_SIZE,
	MSG_CMD_ISP_AE_GET_BIN_BUF,
	MSG_CMD_ISP_AE_GET_FRAME_ID,
	MSG_CMD_ISP_AE_GET_FPS,
	MSG_CMD_ISP_AE_GET_LVX100,
	MSG_CMD_ISP_AE_SET_FASTBOOT_EXPOSURE,
	MSG_CMD_ISP_AE_SET_FAST_CONVERGE_ATTR,
	MSG_CMD_ISP_AE_GET_FAST_CONVERGE_ATTR,
	MSG_CMD_ISP_AE_GET_FAST_CONV_CALIBRATION_INFO,
	MSG_CMD_ISP_AE_SET_SIM_MODE,
	MSG_CMD_ISP_AWB_GET_LOG_BUF,
	MSG_CMD_ISP_AWB_GET_BIN_SIZE,
	MSG_CMD_ISP_AWB_GET_BIN_BUF,
	MSG_CMD_ISP_AWB_SET_SIM_MODE,
	MSG_CMD_ISP_AWB_GET_RUN_STATUS,
	MSG_CMD_ISP_AWB_SET_RUN_STATUS,
	MSG_CMD_ISP_AF_AUTO_FOCUS,
	MSG_CMD_ISP_AF_GET_FV,
	MSG_CMD_ISP_AF_SET_ZOOM_SPEED,
	MSG_CMD_ISP_AF_SET_ZOOM,
	MSG_CMD_ISP_AF_SET_FOCUS_SPEED,
	MSG_CMD_ISP_AF_SET_FOCUS,
	MSG_CMD_ISP_AF_QUERY_FOCUS_INFO,
	MSG_CMD_ISP_SET_BYPASS_FRM,
	MSG_CMD_ISP_GET_BYPASS_FRM,
} MSG_ISP_CMD_E;


#endif
