#ifndef __MSG_SYS_H__
#define __MSG_SYS_H__

#include "msg.h"

typedef enum tagMSG_SYS_CMD_E {
	MSG_CMD_SYS_INIT = 0,
	MSG_CMD_SYS_EXIT,
	MSG_CMD_SYS_BIND,
	MSG_CMD_SYS_UNBIND,
	MSG_CMD_SYS_GET_BIND_BY_DEST,
	MSG_CMD_SYS_GET_BIND_BY_SRC,
	MSG_CMD_SYS_GET_VERSION,
	MSG_CMD_SYS_GET_CHIP_ID,
	MSG_CMD_SYS_GET_POWER_REASON,
	MSG_CMD_SYS_GET_CHIP_VERSION,
	MSG_CMD_SYS_SET_VI_VPSS_MODE,
	MSG_CMD_SYS_GET_VI_VPSS_MODE,
	MSG_CMD_SYS_ALIOS_INIT,
	MSG_CMD_SYS_ALIOS_EXIT,
	MSG_CMD_SYS_GET_ALIOS_MEM_STATE,
	MSG_CMD_SYS_FB_ON_SC,
	MSG_CMD_LOG_SET_LEVEL_CONF,
	MSG_CMD_LOG_GET_LEVEL_CONF,
} MSG_SYS_CMD_E;


#endif
