#ifndef __MSG_VO_H__
#define __MSG_VO_H__

#include "msg.h"

typedef enum tagMSG_VO_CMD_E {
	MSG_CMD_VO_SET_PUBATTR,
	MSG_CMD_VO_GET_PUBATTR,
	MSG_CMD_VO_ENABLE,
	MSG_CMD_VO_DISABLE,
	MSG_CMD_VO_ENABLE_VIDEOLAYER,
	MSG_CMD_VO_DISABLE_VIDEOLAYER,
	MSG_CMD_VO_SET_VIDEOLAYERATTR,
	MSG_CMD_VO_GET_VIDEOLAYERATTR,
	MSG_CMD_VO_SET_CHNATTR,
	MSG_CMD_VO_GET_CHNATTR,
	MSG_CMD_VO_SET_DISPLAYBUFLEN,
	MSG_CMD_VO_GET_DISPLAYBUFLEN,
	MSG_CMD_VO_ENABLE_CHN,
	MSG_CMD_VO_DISABLE_CHN,
	MSG_CMD_VO_SET_CHNROTATION,
	MSG_CMD_VO_GET_CHNROTATION,
	MSG_CMD_VO_SEND_FRAME,
	MSG_CMD_VO_CLEAR_CHNBUF,
	MSG_CMD_VO_SHOW_PATTERN,
	MSG_CMD_VO_SHOW_CHN,
	MSG_CMD_VO_HIDE_CHN,
	MSG_CMD_VO_GAMMA_LUT_UPDATE,
	MSG_CMD_VO_GAMMA_LUT_READ,
	MSG_CMD_VO_PAUSE_CHN,
	MSG_CMD_VO_RESUME_CHN,
	MSG_CMD_VO_DEV_IS_ENABLE,
	MSG_CMD_VO_SUSPEND,
	MSG_CMD_VO_RESUME,
	MSG_CMD_VO_QUERYCHNSTATUS,
	MSG_CMD_VO_GETCHNPTS,
	MSG_CMD_VO_GETCHNFRAMERATE,
	MSG_CMD_VO_SETCHNFRAMERATE,
	MSG_CMD_VO_GETBTPARAM,
	MSG_CMD_VO_SETBTPARAM,
	MSG_CMD_VO_GETLVDSPARAM,
	MSG_CMD_VO_SETLVDSPARAM,
	MSG_CMD_VO_GETLAYERPROCAMPCTRL,
	MSG_CMD_VO_GETLAYERPROCAMP,
	MSG_CMD_VO_SETLAYERPROCAMP,
} MSG_VO_CMD_E;

#endif
