#ifndef __MSG_RGN_H__
#define __MSG_RGN_H__

#include "msg.h"

typedef enum tagMSG_RGN_CMD_E {
	MSG_CMD_RGN_CREATE = 0,
	MSG_CMD_RGN_DESTROY,
	MSG_CMD_RGN_GET_ATTR,
	MSG_CMD_RGN_SET_ATTR,
	MSG_CMD_RGN_SET_BITMAP,
	MSG_CMD_RGN_ATTACH_TO_CHN,
	MSG_CMD_RGN_DETACH_FROM_CHN,
	MSG_CMD_RGN_SET_DISP_ATTR,
	MSG_CMD_RGN_GET_DISP_ATTR,
	MSG_CMD_RGN_GET_CANVAS_INFO,
	MSG_CMD_RGN_UPDATE_CANVAS,
	MSG_CMD_RGN_INVERT_COLOR,
	MSG_CMD_RGN_SET_CHN_PALETTE,
	MSG_CMD_RGN_GET_CTX,
	MSG_CMD_RGN_SET_IONSIZE,
} MSG_RGN_CMD_E;

#endif
