[CVI_BOOT]
misc_device = /dev/mmcblk0p4

[AB_PARTITIONS]
boot      = /dev/mmcblk0p1,/dev/mmcblk0p2
rootfs    = /dev/mmcblk0p5,/dev/mmcblk0p6
rootfs_rw = /dev/mmcblk0p7,/dev/mmcblk0p8

[UPGRADE]
boot_image    = /data/ota/raw_images/boot.img
rootfs_image  = /data/ota/raw_images/rootfs.img
rootfs_rw_image = /data/ota/raw_images/rootfs_rw.img